apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-defaults
  namespace: default
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "20"
